### ISSUE TITLE
Unable to initialize Algorithm on astra.algorithm.create for FDKReconstruction.py

### ISSUE THREAD

**Issue by PranjalSahu** [cicwi/WalnutReconstructionCodes#2]
Hello on creating the astra.algorithm.create in the FDKReconstruction.py file I am getting the following error.
Can someone please run the master branch to confirm that they are able to run the code?

On some online research, I found that Astra does not accept cone_vec with FDK_CUDA. Just wanted to confirm that the code in the master branch works for the author.

--------------------------------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-12-031b3075a2aa> in <module>()
      7 cfg_fdk['option'] = {}
      8 cfg_fdk['option']['ShortScan'] = False
----> 9 alg_id = astra.algorithm.create(cfg_fdk)
     10 
     11 # run FDK algorithm

~/anaconda3/envs/tensorflow/lib/python3.6/site-packages/astra/algorithm.py in create(config)
     34 
     35     """
---> 36     return a.create(config)
     37 
     38 def run(i, iterations=1):

astra/algorithm_c.pyx in astra.algorithm_c.create()

Exception: Unable to initialize Algorithm.
-------------------------------------------------------------------------------------------------

**Comment by wjp** [comment]
Hi,

You will need a development version of Astra (1.9.0 or higher) to use this code. If you are using conda, this is available through our `astra-toolbox/label/dev` channel.

**Comment by FelixLucka** [comment]
Thanks for spotting this, I've run the code only with the development version. I will update the "Requirements" section in the readme (I mentioned there that the development version is necessary to obtain matching intensities but was not aware it throws an error with the standard version).

**Comment by dariyaisl** [comment]
Hello, is it resolved? I am still facing the problem on that stage, could you please help to run the code?

**Comment by FelixLucka** [comment]
Yes, I think this is resolved. I just tested the script using an environment with the current normal version of ASTRA and an environment with the current development version and it worked in both cases. I will edit the "Requirements" section in the readme.
@dariyaisl : which version of ASTRA are you using and what is the exact error you get?

**Comment by maikeros** [comment]
Hey @FelixLucka , 
I also have problems with this. I installed the astra-version 2.1.2 and the FDK algorithm works for CBCT, but all the other algorithms I tried to use gave an error message like this:
python reconMitPixelID.py 
Traceback (most recent call last):
  File "/home/student/Desktop/Maike/GateCTs/ergebnisse/tests/MiniSimulation/reconMitPixelID.py", line 47, in <module>
  File "/home/student/anaconda3/lib/python3.10/site-packages/astra/algorithm.py", line 36, in create
    return a.create(config)
  File "astra/algorithm_c.pyx", line 64, in astra.algorithm_c.create
Exception: Unknown Algorithm.

Tested it for SART, ART, SIRT, CGLS and Gridrec. Only FDK works.

Do you have an idea how to solve this?

Kind regards, 
Maike

**Comment by FelixLucka** [comment]
Hi @maikeros : Just to double check: Not all of the methods you mention are implemented for 3D, cf. [astra documentation](https://www.astra-toolbox.com/docs/algs/index.html). Did you switch `AGD-PLUGIN` in line 161 of `GroundTruthReconstruction.py` to  `SIRT3D_CUDA` or `CGLS3D_CUDA`? For me, that works (you might want to adjust the number of iterations to get a good solution, but the code runs without errors). I just tested that with a fresh conda environment using python 3.10.13 and astra 2.1.2.
