### ISSUE TITLE
"scan_geom_original.geom" files in datasets

### ISSUE THREAD

**Issue by PeterPaang4** [cicwi/WalnutReconstructionCodes#7]
Dear GitHub Blogger,

I hope this message finds you well. I am reaching out to inquire about the process of obtaining "scan_geom_original.geom"and "scan_geom_original.geom"files in walnut's datasets, as I noticed you have used "scan_geom_original.geom" on this topic on your "FDKRconstruction" I am particularly interested in learning more about it.

Could you please provide some guidance or reference materials on how  "scan_geom_original.geom"and "scan_geom_original.geom"files are obtained? My understanding in this area is limited, and I believe your expertise could greatly assist me in gaining clarity.

If it's convenient for you, would you mind sharing some methods or documentation links related to obtaining geom files? I genuinely appreciate your time and assistance.

Thank you very much!

Warm regards,

**Comment by FelixLucka** [comment]
The generation and usage of files are described in detail in [the paper](https://www.nature.com/articles/s41597-019-0235-y) that describes the data set. Please clarify what aspects you need more information about.

**Comment by PeterPaang4** [comment]
Thanks for your reply!I have resolved this issue.
